version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: guacamole_product
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"