server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/guacamole_product?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
      format_sql: true
    open-in-view: false
logging:
  level:
    root: info